<?php
/**
 * @package Helios Calendar
 * @license GNU General Public License version 2 or later; see LICENSE
 */
	define('isHC',true);
	define('isAction',true);
	include_once('../loader.php');
	include_once(HCLANG.'/public/rss.php');	

    if($hc_cfg[106] == 0)
        go_home();

    $lQuery = $cQuery = $catIDs = $cityNames = '';
	$sID = (isset($_GET['s']) && is_numeric($_GET['s'])) ? cIn($_GET['s']) : 0;
	$feedName = $hc_lang_rss['FeedLabel' . $sID];
	$tzRSS = str_replace(':','',HCTZ);

    if(isset($_GET['l'])){
        $catIDs = array_filter(explode(',',$_GET['l']),'is_numeric');
        $cats = (count($catIDs) > 0) ? cIn(implode(',',$catIDs)) : '0';
        $lQuery = " AND c.PkID IN (".$cats.")";
    }
    if(isset($_GET['c'])){
        $cityNames = array_map('cIn',array_map('strip_tags',explode(',',$_GET['c'])));
        $cQuery = " AND (e.LocationCity IN ('".implode("','",$cityNames)."') OR l.City IN ('".implode("','",$cityNames)."'))";
    }
	
	if(!file_exists(HCPATH.'/cache/car'.SYSDATE.'_' . $sID)){
		$files = glob(HCPATH.'/cache/car*_' . $sID);
		if(COUNT($files) > 0 && $files[0] != ''){
			foreach($files as $filename){
				unlink($filename);
			}
		}
        
        $query = "SELECT DISTINCT e.PkID, e.Title, e.Description, e.StartDate, e.StartTime, e.SeriesID, e.Image, e.EndTime, l.Name, GROUP_CONCAT(c.CategoryName)
                    FROM " . HC_TblPrefix . "events e
                        LEFT JOIN " . HC_TblPrefix . "eventcategories ec ON (e.PkID = ec.EventID)
                        LEFT JOIN " . HC_TblPrefix . "categories c ON (ec.CategoryID = c.PkID)
                        LEFT JOIN " . HC_TblPrefix . "locations l ON (e.LocID = l.PkID)
                    WHERE e.IsActive = 1 AND
                        e.IsApproved = 1 AND e.StartDate >= '" . cIn(SYSDATE) . "' AND c.IsActive = 1
                        GROUP BY e.PkID, e.Title, e.Description, e.StartDate, e.StartTime, e.SeriesID, e.EndTime, l.Name";
        $result = doQuery($query . " ORDER BY StartDate, StartTime LIMIT ".$hc_cfg[2]);
		
		ob_start();        
		$fp = fopen('../cache/car'.SYSDATE.'_' . $sID, 'w');        
        echo '
<!-- Generated by Helios Calendar '.$hc_cfg[49].' on '.SYSDATE.' '.SYSTIME.' -->
<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
    <link>'.CalRoot.'/</link>
    <atom:link href="'.CalRoot.'/rss/?sID='.$sID.'" rel="self" type="application/rss+xml" />
    <generator>Helios Calendar</generator>
    <docs>'.CalRoot.'&#47;index.php&#63;com=tools</docs>
    <description>'.cleanXMLChars($hc_lang_rss['Upcoming']).'</description>';

    if(hasRows($result)){
    echo '
    <title>'.cleanXMLChars($hc_lang_rss['Custom']).'</title>';
    $cnt = 0;
    while($row = mysql_fetch_row($result)){
        $description = $row[2];
        $description = str_replace("</p><p>", "<br />", $description);
        $description = str_replace("</div><div>", "<br />", $description);
        $description = strip_tags(html_entity_decode($description));
        $description = ($hc_cfg[107] > 0) ? clean_truncate($description,$hc_cfg[107]) : $description;
    
        $categories = explode(",",$row[9]);//filtering out ACE
        switch (count($categories)){
            case 0:
                $category = 'No Category';
                break;
            case 1:
                $category = substr($categories[0],3);
                break;
            default:
                $category = (substr($categories[0],-4) != '_ACE') ? substr($categories[0],3) : substr($categories[1],3);
                break;
        }
       if(isset($row[7]))
        {
            $endTime = date("g:i A",strtotime(stampToDate($row[3].' '.$row[7],"%d %b %Y %H:%M:%S")));
        }
        else{
            $endTime = "";
        }
        $comment = ($hc_cfg[25] != '') ? '<comments><![CDATA['.CalRoot.'/index.php?eID='.$row[0].'#disqus_thread'.']]></comments>' : '';
        echo '
<item>
        <title>'.cleanXMLChars(stampToDate(cOut($row[3]), $hc_cfg[24]))." - ".cleanXMLChars(cOut($row[1])).'</title>
        <link><![CDATA['.CalRoot.'/index.php?eID='.$row[0].']]></link>
        <description>'.cleanXMLChars(cOut($description)).'</description>
        '.$comment.'
        <guid>'.CalRoot.'/index.php&#63;eID='.$row[0].'</guid>
        <pubDate>'.cleanXMLChars(stampToDate($row[3].' '.$row[4], "%a, %d %b %Y  %H:%M:%S").' '.$tzRSS).'</pubDate>
        <date>'.cleanXMLChars(stampToDate($row[3], "%B %d")).'</date>
        <startTime>'.date("g:i A",strtotime(stampToDate($row[3].' '.$row[4],"%d %b %Y %H:%M:%S"))).'</startTime>
        <endTime>'.$endTime.'</endTime>
        <location>'.$row[8].'</location>
        <category>'.cleanXMLChars($category).'</category>
        <eventName>'.cleanXMLChars(cOut($row[1])).'</eventName>
</item>';
    ++$cnt;
}
} else {
    echo '
    <title>'.$hc_lang_rss['RSSSorry'].'</title>
    <item>
        <title>'.$hc_lang_rss['RSSNoEvents'].'</title>
        <link>'.CalRoot.'/</link>
        <description>'.$hc_lang_rss['RSSNoLink'].'</description>
        <guid>' . CalRoot . '/</guid>
    </item>';
}
echo '
</channel>
</rss>';

		fwrite($fp, ob_get_contents());
		fclose($fp);
		ob_end_clean();
        
        
	}
	header('Content-Type:application/rss+xml; charset=' . $hc_lang_config['CharSet']);
	echo '<?xml version="1.0" encoding="'.$hc_lang_config['CharSet'].'"?>';
	include(HCPATH.'/cache/car'.SYSDATE.'_'.$sID);
?>